Issue 420: Typo changes and added notification settings
100mslive/100ms-web pull request #430
Opened 2021-10-06 15:02 UTC by mani-rsg

- [x] Rename Layout Settings above to UI Settings
- [x]  Renamed title from Participant in View to UI settings and make participant text down to the title above the slider (made changes in [@100mslive/hms-video-react](https://github.com/100mslive/hms-video-react/issues/397))
- [x]  Add new section for Notifications with checkboxes for Peer Join/Peer Leave/New Message/Errors (made changes in [@100mslive/hms-video-react](https://github.com/100mslive/hms-video-react/issues/397))
- [x]  Allowed only the selected notifications to be sent from here - https://github.com/100mslive/100ms-web/blob/main/src/views/components/notifications/Notifications.jsx

Attached below screenshots for reference:

<img width="1077" alt="Screenshot 2021-10-06 at 8 30 13 PM" src="https://user-images.githubusercontent.com/72298612/136229816-8c25d361-5da3-494b-b67c-aaac898e1588.png">
<img width="231" alt="Screenshot 2021-10-06 at 8 30 58 PM" src="https://user-images.githubusercontent.com/72298612/136229978-f1a8e008-470a-44fc-843b-115bb4e91acf.png">

2021-10-07 05:10 UTC, raviteja83 requested changes

2021-10-07 05:10 UTC, raviteja83 commented on src/store/AppContext.js
> +      return {...prevState};
`{
	...prevState,
 	subscribedNotifications: {
 		...prevState.subscribedNotifications, 
 		[notification.type]: notification.isSubscribed
 	}
 }`

2021-10-07 05:10 UTC, raviteja83 commented on src/views/components/MoreSettings.jsx
> +    console.log(count);
remove console

2021-10-07 05:10 UTC, raviteja83 commented on src/views/components/notifications/Notifications.jsx
>          if (window.HMS.notifications?.peerLeft) {
can you remove this part now. it is not needed as UI changes are done now. Also remove notifications from window.HMS in `FeatureFlags` component

2021-10-07 05:10 UTC, raviteja83 commented on src/store/AppContext.js
> +    subscribedNotifications: { "PEER_JOINED": true, "PEER_LEFT": true, "NEW_MESSAGE": true, "ERROR": true }
make peer_join and peer_left  as false by default

2021-10-08 07:06 UTC, triptu commented
@mani-rsg can you please send your resume as well to tushar@100ms.live :) ?

2021-10-08 08:32 UTC, raviteja83 commented
@mani-rsg can you update @100mslive/hms-video-react version

2021-10-09 05:07 UTC, raviteja83 approved these changes

2021-10-09 05:08 UTC, merged